language: go

sudo: false

go: 1.14

install:
  - make dep-dev

script:
  - GOOS=linux  GOARCH=amd64 make --debug EXECUTABLE=pxe-pilot-linux-amd64
  - GOOS=linux  GOARCH=arm   make --debug EXECUTABLE=pxe-pilot-linux-arm
  - GOOS=darwin GOARCH=amd64 make --debug EXECUTABLE=pxe-pilot-darwin-amd64

deploy:
  provider: releases
  api_key:
    secure: NOlitwe+OTHhUHwKTDrux2aUkyvvz/AC6Xjtb1uFM6f7x26XyeGp0DPgPPSaGIxJKXKxnSSVd03GS2oZ6LnUcwASWhkizd0d91IiGNfmsdUYvc+x/kuPGBNUqEkHmi/YswBXak8ZFE75ci3VYtdGP6j2Sjp/tjO0sHqjj5wyaD3rhnNvjdrBWftC3TPNACM856y2Yn/Fb2zXTyCnEtURl7XfZHyYDLDFmWVgI5igtYIbFJ9F9iF4oHPT2cXMKJvgMIROH0gdEwiVx32+bnuBu2NmHVab3/8g54b0RJg39MnBd0KPVJ2dxue92KmEEpA6tqS1QxohAqTGlU1uVqHlPvxN5jLfjkaewW+ICGQ85zWYij72KbG+VoJuurvb5DD/ajHdnX2dv4olQKJw+7YpgtNI8zrjXRoQCCzeq50vJspbkxYEWeG5loGefpnMwcRZfF8qKJMioHOZvXmbDz5s5jP4Svw6ASpAq9tkDKcwiMpb3HtFVA6X8fqV/MEyMNgXVQUVeNQqDyfqDtBrqwKySvEUyvpsSYA1lzakx8KejsIwhpNhvCUSL6xRq3qpv7i2hiReXNycXnA7t7flUn6ZMtUVNFuBHICwO/6e+ISVKhmzLAKo/WiRLr/o+9xHWTSBvIkbASxezhvjxQqEsTBCUjnU6/18eRR7nadNbrHPw8c=
  skip_cleanup: true  
  file:
    - pxe-pilot-linux-amd64
    - pxe-pilot-linux-arm
    - pxe-pilot-darwin-amd64
  on:
    tags: true
